### ISSUE TITLE
[BUG:]QA/QE: Broken import statement in environment.py

### ISSUE THREAD

**Issue by ByteOtter** [ByteOtter/OtterDen#66]
# Found an issue? Please let us know!

when trying to launch any testscenario, behave throws the error "module test_utils not found" despite the directory being where it should be. This directory holds all necessary utility functions selenium needs to set up correctly so not importing it borks the testsuite.

### Please tick the applicable box(es) regarding the kind of bug you found:

- [x] Broken feature
  - [ ] Login/Logout system
  - [ ] Database broken
  - [ ] Post-related problem
  - [ ] Unusable route
- [ ] UI Bug
- [ ] Wrong documentation
- [ ] Broken dependency

### Steps to reproduce

1. try to run behave testsuite/features/core/init.py
2. get greeted by error message

### Links

This issue is connected to Issue [#53 ](https://github.com/ByteOtter/OtterDen/issues/53)

### Additional context

Stacktrace:

```
Exception ModuleNotFoundError: No module named 'test_utils'
Traceback (most recent call last):
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/bin/behave", line 8, in <module>
    sys.exit(main())
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/runner.py", line 808, in run_with_paths
    self.load_hooks()
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/runner.py", line 784, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/home/chris/Dev/PrivateProjects/LogBlog/env/lib64/python3.10/site-packages/behave/runner_util.py", line 386, in exec_file
    exec(code, globals_, locals_)
  File "testsuite/features/environment.py", line 10, in <module>
    from test_utils.utils_web import get_browser
ModuleNotFoundError: No module named 'test_utils'
```

**Comment by ByteOtter** [comment]
to run behave successfully apparently the user needs to be inside the testsuite folder.
this behavior is to be expected as Cucumber handles the same.
